// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccordionController from "./accordion_controller"
application.register("accordion", AccordionController)

import AiController from "./ai_controller"
application.register("ai", AiController)

import HamburgerController from "./hamburger_controller"
application.register("hamburger", HamburgerController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import RadioSelectController from "./radio_select_controller"
application.register("radio-select", RadioSelectController)

import RedirectController from "./redirect_controller"
application.register("redirect", RedirectController)
