// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccordionController from "./accordion_controller"
application.register("accordion", AccordionController)

import AiController from "./ai_controller"
application.register("ai", AiController)

import HamburgerController from "./hamburger_controller"
application.register("hamburger", HamburgerController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MotionController from "./motion_controller"
application.register("motion", MotionController)

import PreviewsController from "./previews_controller"
application.register("previews", PreviewsController)

import RadioSelectController from "./radio_select_controller"
application.register("radio-select", RadioSelectController)

import ReactionHoverController from "./reaction_hover_controller"
application.register("reaction-hover", ReactionHoverController)

import RedirectController from "./redirect_controller"
application.register("redirect", RedirectController)

import RevealController from "./reveal_controller"
application.register("reveal", RevealController)
